version: "3.6"
services:
  rust:
    build:
      context: ./docker/rust/
      dockerfile: Dockerfile
    volumes:
      - ./:/rust-api
    container_name: rust_api

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker/mysql/my.conf:/etc/mysql/conf.d/docker.cnf
    ports:
      - 3306:3306
    container_name: rust_mysql
